{
 "title": "SDK Mine",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Activity Failed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_samples_temporal_activity_execution_failed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity Failed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_samples_temporal_activity_execution_failed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "corrupted_signals",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "corrupted_signals", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "num_pollers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_pollers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "workflow_cancelled",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "workflow_cancelled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "workflow_completed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "workflow_completed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "worker_start_activity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_samples_temporal_worker_start{worker_type=\"ActivityWorker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "worker_start_workflow",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_samples_temporal_worker_start{worker_type=\"WorkflowWorker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "worker_start_workflow",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_samples_temporal_worker_task_slots_available{worker_type=\"WorkflowWorker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "worker_start_activity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_samples_temporal_worker_task_slots_available{worker_type=\"ActivityWorker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "workflow_failed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workflow_failed{worker_type=\"ActivityWorker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "activity_execution_latency",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(temporal_samples_temporal_activity_execution_latency_bucket[5m])) by (activity_type, namespace, task_queue)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}