{
 "title": "SDK Metrics Updated",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Namespace" },
   { "name": "WorkflowType" }
  ]
 },
 "panels": [
  {
   "title": "Worker Slot (ActivityWorker)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_samples_temporal_worker_task_slots_available{worker_type=\"ActivityWorker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Slot (LocalActivityWorker)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_samples_temporal_worker_task_slots_available{worker_type=\"LocalActivityWorker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Slot (WorkflowWorker)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_samples_temporal_worker_task_slots_available{worker_type=\"WorkflowWorker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sticky Cache Size(AubPostUserWorkflow)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_samples_temporal_sticky_cache_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Schedule to Start Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(temporal_samples_temporal_workflow_task_schedule_to_start_latency_bucket[5m])) by (activity_type, namespace, task_queue, workflow_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Schedule to Start Sum",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(temporal_samples_temporal_workflow_task_schedule_to_start_latency_bucket[5m])) by (activity_type, namespace, task_queue, workflow_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity Schedule to Start ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(temporal_samples_temporal_activity_schedule_to_start_latency_sum[5m])) by (activity_type, namespace, task_queue, workflow_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity Schedule to Start ",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(temporal_samples_temporal_activity_schedule_to_start_latency_sum[5m])) by (activity_type, namespace, task_queue, workflow_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Overview ($Namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Vs Failures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(temporal_request{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(rate(temporal_request_failure{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "RPC Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) ((rate(temporal_request{namespace=~\"$Namespace\"}[5m])))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "RPC Failures Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(temporal_request_failure{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "RPC Latencies ($Namespace)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, operation, le) (rate(temporal_request_latency_bucket{namespace=~\"$Namespace\"}[5m])))",
     "legendFormat": "{{ namespace }} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Workflow Completion",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(temporal_workflow_completed{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(rate(temporal_workflow_failed{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(rate(temporal_workflow_canceled{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "canceled"
      },
      {
       "expr": "sum(rate(temporal_workflow_continue_as_new{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "continued_as_new"
      }
     ]
    },
    {
     "title": "Workflow End-To-End Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_endtoend_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
       "legendFormat": "{{ namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Success By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_completed{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Failures By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_failed{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }} - {{ workflow_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Task Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Workflow Task Throughput By WorkflowType",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_task_queue_poll_succeed{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Throughput By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_workflow_task_queue_poll_succeed{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Empty Polls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_workflow_task_queue_poll_empty{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "Empty Poll - {{ namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Backlog By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Backlog By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
       "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Failed By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_workflow_task_execution_failed{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Failed By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_task_execution_failed{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Execution Latency By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Execution Latency By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
       "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Replay Latency By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_replay_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Replay Latency By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_replay_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
       "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Activities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Activity Throughput By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(temporal_activity_execution_latency_count{namespace=~\"$Namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Activity Throughput By Activity Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, activity_type) (rate(temporal_activity_execution_latency_count{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{ namespace }} - {{ activity_type }}"
    }
   ]
  },
  {
   "title": "Failed Activity by Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, activity_type) (rate(temporal_activity_execution_failed{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{ namespace }} - {{ activity_type }}"
    }
   ]
  },
  {
   "title": "Activity Execution Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_execution_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, activity_type, le))",
     "legendFormat": "{{ namespace }} - {{ activity_type }}"
    }
   ]
  },
  {
   "title": "Activity End-To-End Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_endtoend_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, activity_type, le))"
    }
   ]
  },
  {
   "title": "Activity Task Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Empty Activity Polls By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_activity_poll_no_task{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Activity Task Backlog By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))"
      }
     ]
    },
    {
     "title": "Activity Task Backlog By Activity Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, activity_type, le))",
       "legendFormat": "{{ namespace }} - {{ activity_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sticky Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sticky Cache Hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_sticky_cache_hit{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Miss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_sticky_cache_miss{namespace=~\"Namespace\"}[5m]))",
       "legendFormat": "{{ namespace  }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Forced Eviction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_sticky_cache_total_forced_eviction{namespace=~\"Namespace\"}[5m]))",
       "legendFormat": "{{ namespace  }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (temporal_sticky_cache_size)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  }
 ]
}